language: scala
scala: 2.12.6
jdk: oraclejdk8

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
    - '.hoarder-cache'

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "PBA5ez55eWefabbL8Wip1LZ40vwNBZ6TcP+vg+5VDxTx09Z3Nv2iVbe3djAGt1+jgzgDJiiT9teNeD7SfEEHrajr0CQ9mAIcWSXLNgzemG0eRd4ph3FT8UJ2cl5zxJP1jfBGTtxwJZTod9TyLcsXSYLu+LRazRny1PCPldaXhgEtQ6K9mQKuyBXyd5QvUoTbCK4i5DT5Fjh3hfFbuesllhwa+eLGQElfQP6kAtqo5Mk9UashV86ss+xRCs611aqUVbRtwHEhIjkStdaeBkeHvEJIA83NCBmyXDJepUdGkvlKnNFg+esAkfOm9YXzUiQC9F5d3YvSJwMvGAx+u8EAV+DK0XIc/vgJyLp57Ibt/gdN6VuCkNQwr7DkvXHI8XWs8X4I/3gWPNI6ZEJtcr6+licYEJqlUofwmh+2u0TbGmy8ArcchoQ2Rvi2HM/DxbqJPBinbvlZ/Al/QmLAp3sR7DHNzZiFyKNdpTOUm0TWJQsVu8IeAd37ot7ewIqyr2H+Ct+GZuQp5eNXfA0VUs9Js1aJ0iBccHVtpt5M//qD1SYxuNS9v50cjYfcIO20gTypgBpO+eHO7ec+9pNAoaxiAh29L4uMjoD6G/60HolZ1O4VP0no+LdIiDx1xbPCnnywrmibnt5KljD1Zg4dJTd5lsu8KDFSI1W4LxRIr0x/5mg="
    # GITHUB_TOKEN
    - secure: "HxXAcIosGWH1/CwW97stLp8PuAqA55gi0ZI9YqjBj6Rgw5ZFd/mIDDpzrcqFZZVeWbw33z6G4DND2OyGP9Xp+F5pg61p536dNtMqir4qID6Vbq0IVOKLI6z4yNvsso/LiT6XWMXIXfKb/f3SvBXTX9QTUp7v+DCjf4VZDMe447gPI3u+FKKvbSNRMCsYn+TyGYIWCUGJY343Ty1qHlqv+6vY0j5tja91pjE4jJoYudzHu+ZsSUmfl9HeSWipFvvBSC36E86RQhug/4eRgGBoWXyPtYT29RJx48t/QwJQUCOQdMwlnqR8LsKkHNK4DLz+YZZ8cs/1EL1zWLhKPav/Nnb96O7VBALK5slY2Y90yCikvQ0s/LnhAgJKp3I+uaMCR7yUhoWWAUjlC+7N5Bpc5qpLUk0O1ywl7ocaT1HHlYUM9iQUpia5hw0BtPNskp5atTYAND2dqaoniiDL+n2zFRJZsJNQblX5IJkVQo7q8Q2zUlMvYRd6KXH4A8pxqeyPFhwvmDKspsI0KyTVmNP5pinYC/Lo0HnxMb0uFT42lrq5XVBDyDaMOuWMu3dWWUxw0A7Ha2iKHW1bMMdfu0wS66y3dhW2EvTd2HF26z/DAKpGUzK8sJkAjh+qLZlCRdkUmpvOXUoU4DoGyhcOUTTejGolxdhBJ3nhFGCLOhltSds="
    # GITHUB_ACCESS_TOKEN
    - secure: "bCnxDkEY+57bXXkhNsldZgcDwx3RCmiPaKRkq6Eox4UM68GHlp/tQt4lcA7A5o/f+S6ZDqB8P/AksBgz6oXBFmLvPUHL3DmE0V5yfGBPVf6myFEph8btbHueUWP2DzCwfOTYGKvvMCtoQrzxpmc9NDDdM5XCRMC8ERMWJPuSuVbVOgDaxnYsoyTTvAmHNr7kwGcLhI0t8Kxl8bGoH8qXLZDG+/ixjoH1yR1V2zyoG5Nd5/rXFDEmp122LW8xZDpAIOxjgcnh1F6iSH4cNU5t8niRpvG1jkSZyPJAkGy6ReeQ5xUHGxOksEFPYh9+RzfDqOH2bN6GvFKSQmqAZVy8wXXA7Dt8JvzgPtp1FBCdZctVBXwUy5q4VvuUwap/QwdKL7lgPteK0G54xknBvtynJWQzU2tP/YZrvjNhZuq4oKf8J+hQ4CSpHTY/mpuvbatFRgCDyKZ/xiWAS09dR06TgVGDFtI2kBfu1JSG0mfpzDyCmfGu/DCXmuLuLlK6izoPTuh0qzHxtC6PgbUpZgVjiLQPXZfB+gMg1W82ws39BH4UMY5CwdgaCH2LqowiPUzFdShXJweD/6kPytgVr8bunSyfn+NDm5b1/wU8HdmXNoAg8WJTh5rux/PbyhZFavqUAVhiipyNGULK+D+QSbnzlIDlTdsC/vmn/Tbdsh06DmM="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "PkHrrBkXJyLwNhKqwFItSA8oJHwiZnaRaJcnxl8OItCspfEvZC1Vww8NODp/OzjIWDVhN0GEd82hrNfokz17Wn/Wgx/n+DPX09GUHfJyaFw7ji4+1JEjar8YzYWoTgi0Qm07Aae5p4TuXIRzPE92dB3Frzbxnsl8pPk8FlzWQDhkDeIfWgW+zAi+BhWSAhCd8i+/S+IrApfOLx7Rg01p+V55PRuVBV4r2Ek6+H/5Ypex0Z5/piezUxsMvzaW3WIghhtpBlOqAr2QR+3MhcEkFj8myzN/fePHbSNKG/0YHDh/wApT/PxtXj8L132gghVVUGw6HWwMuGx8NlylZXK+P1pUZM0wTZ3KFSfYMzvB8U/MCOL6mNZTf9TUMGWRHoFKLvPkLRZTuBeco2I2ZRj2az9BkueCtT7IxRZdiihGU2SWIkWyzTrDeUgGtYOzfXtyAKvqqcUnVdQtWjg4+l1MqyZbggZ9xwOxcFpIME3a2Pa8s6knCap52F7MJ/SHlhbW87gtpTJ38aoZlgEJ3h9pQW4PQR51ktUTIO7DLoH5VESapHBUJ4aAXL1/HORNawj4H5R6AsR2TIsflknro3MZKq+VJmqfELjFdRGwxMaTnXv08FtPcq0RUm/2Z78jJtpHoqq/7BiFywK8l3/v3afoRf87D5YXqzWK/bLBGslzIKA="

install:
  - $SBT transferCommonResources
  - scripts/commonSetup

jobs:
  include:
    - stage: test
      script:
        - set -e
        - $SBT ++$TRAVIS_SCALA_VERSION test

    - stage: publish
      env:
      script:
        - set -e
        - $SBT transferPublishAndTagResources
        - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-datasource-azure'
        - bumpInDownstream() { echo $1 > slamdata-azure-version; }
        - export -f bumpInDownstream
        - scripts/bumpDependentProject slamdata slamx bumpInDownstream
      git:
        depth: false

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
