language: scala
scala: 2.12.6
jdk: oraclejdk8

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
    - '.hoarder-cache'

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "RPGQkv55XTNb6V999gNYO/8N6fguLZ2F9FjN+QsqtpxHtljYmgQjqMWHArKVpPtUoOx07IeoU6J7TkTXXE6yeEISm5FOSLDfWElHYL96Pk005qfFprl2RLZ20YQWzAkc7N+2Q8joJ0PhXJZd5x8v330cyYRmjrjm+gEi565J07PTc+78NpCDFlW5fgQaq6luKn7MfPLxVzujQg1Hkw4pjlde8sobJ9J8Lkgc26tgeMF/rLIa1MAg5kzMpc5QNNHcvKhunEAozGzhVc+qXZZ3OiH8n1IAZrjSv44XvHHBKltkhPPDRaqSomSPksfUImvu5Ci2YAnRIMWpCsXzML5I2/WS7MpGITIuNz+iQjCYdUrcLj+SW3np3cLu3Y0z+pBHJniIJ5WqjKSZ5DSdVWDq55/kIDiiIKKnjNjhbmKY2r/EN1Yjcujpg0wEUB98Msz7PnNUi7pBud9+x5zhuAU1DBvq0GRSR1t5Pi7NWlarnGkMxe+Hcgn5fZ1hBCe0XmoaIvfxYjVq5iDhftiqVCYnvq+iSzFY8mmKgY5eeGiGS1yx9xFcSgMG4x4fxEhPSzggzKE1aIFUcOiFFDW27mcKlqCl8lfg+dPLxa1ZpJ4+NOfanxgCtYAJUOQ20X9gEh3pGo9lLYvvM2zL3VsCdpaxVKuOeMfOmrz7DbNR0lMBE8Q="
    # GITHUB_TOKEN
    - secure: "fNnRJPoHt3a76Qs2CjtYcgi1zQ4s7sLRk2byb/Jiqz1A3rW7Ahu9il86YcQMarInCH8ndBbdiD3N6jTmCLhj/CsXVhspiBs1aS+LUjUU8WdIEypb9P6QvdrJF5efC3CP8jt/jT6qq/qW0Ue5ZNEm6sd0IZ3fQPskzxXJbGXO0S2M1zAuGyzsGGh0RCOgcBNfYIdJY+rPf6SrsGsq+lvR7zhNAPZDCasurH6mxzY12d02BxQlIwBlX7l5LjqqBJrHIBXr/xYh3ezDnM7LpA4wgaNJEf1fKx9lWn8CeA0gZ0pzMmIlBG/zbTkIfV0DH86n9lYWektvrHBbE+/DIAQ7sYAGjqAKv/BTKqIX+1YlZiugmrpWusnkQCiLnDESOWX7unlXJo3Kpe4V3IGSSxQbXbrTnnbkcI/g/BCnD7y/jr/A9VNe8bzZbR/sk/OiHpL2s+SBnrrlahjMSxkBgC2g9YDanf3w0kXG83MzE7dmGWNxEq9kNnHX0Umofzg4Iaw9Sx4LmxbAw25xwT8DZ6KHaF92xDccQNQYIjzZz01m/BigcfEn/gYwUQ8CkeSRe2gYr1+QFj64BRRy8Y6biBBeqEfwLw+vxOcvfeUrbvhz3SsRrU/ldle3u4DnHjyh56Xp/uF2W+UmZdGCmmm58eNMrs9HqC47lkipLwW9ds/03sI="
    # GITHUB_ACCESS_TOKEN
    - secure: "LW7ZlXHrzH57cpUaTrO8gBNXhF4WJ4sT25Mb3TMuJs21vqBNbrjNsP6XKHgeX2mvW82YW16isVV8kXbSdKI1+MQRBsgOPUpe4sfKX6gNAjR5wAAkl0Wf6VuznWcb5H0AetwEqvaq3G/9BBjkok4F4+HgOXYeOrIpZEqMEMImL/vEvCaOzTB4mDYDUkM3B5riiTKMOGCzfCyKbylOZIt/RHj8Cui1MGi3HKat3f3yxJ+tadKRrzpypmSnRCLbGKVkkP7OGLQCqYYX27+XQTLNVf90a3PqS47gyCWUGp6V6LloD7DAJ6MQkrLVHRdhAUWf0ld6+wstD+ploPWPOv7Y3A+bvxyhVNy+9cYfwWLQG1fDjwkpwYWkxM2zJsOGTE91TzzM8l5bAW2Ar4N3jjmJZRWrz3sQrz0pyvIMGpRi3YGi084cepEy8BbJEx9h0MM7RD7QsyDmvGJyMW7aC7nu6kJ43tsZBNZNjQ1ejcT+ZGs24t9k2sJOv15fIjTF1j/t6YzQb2LtrJCWxUHkMWXHbho/VzzB7T36ZodMhhHZmgAWqDmQTDkygIlANnYntO89pH2ZnYE21nbEtzfV3GNcrbmK1G7q6/MEEBZD/1SJaxPO6LQryKddb/l6RAOVJIC0GpFUS//rGzqRxcsNiZD3XaMXOIf843nb1elkqgD4BeI="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "fF8Kb8oxsDLAtkSXZIAFPq/HDZ/Ae3g6rkMFHHItiXP0Vm1R4TAVIcO4OLwBp6fPmMWIlUT3+a+Xj6LeEGyRcNvpNG/CQxKXT54Kfr9QW9osjXC81OYnNKAUingu/9HMU5YIFeObyC5Yofi+0VM8KCh12faPOUY1HwZqpB6HfYdjC0f61WDjHi8nZoRrUXshim/0CCIcU/jCVuZ1zcClRLNiffgS53ShD/0G0R7koD1o1K5iOyv06eXwf6IDchR1cQ1S+tFGz1ioI/vtei4W7XvE7KQLcwCwChQIYE8C9F41QNzzahHwYIxQ00sQAtomea+Hf8ffGSY4L6dh4lMvFqXYWrfl3kCpb2CGmSp2qoKO+v2PT5cI7vOohK02Ow0tXQ+2HFjxX4rDp62BCivZ8HjqPaAe1mK+b+0TOZzXDMmjfUBtRYCpm8oWBJbqhoBkNIQIYt9i1kz//plr3DfEewkfFkSlHfq46m4zENf7/FzRySZONYEGVhqHTfUMwOZ6up4S+BqPCaMFDE8d5hd3tokUv1DFGiiO2RJchQh6NMVKKrtlyCovol7+AN07aK/f8bk/8RwWRjwidnWZubgsvn4db6DkmJ/f0/w1UDzwFqI+cb1z4kWBHA/EPOtv0G89QQbLevUSbZDQoNFCh3L9Lb/kb5A9hpsyODFIRCirx3U="

install:
  - gem install octokit

  - git config --global user.email "bot@slamdata.com"
  - git config --global user.name "SlamData Bot"

jobs:
  include:
    - stage: test
      script:
        - set -e
        - $SBT ++$TRAVIS_SCALA_VERSION test

    - stage: publish
      env:
      script:
        - set -e
        - $SBT transferPublishAndTagResources
        - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-datasource-azure'

      git:
        depth: false

after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST != "false" ] && [[ $TRAVIS_PULL_REQUEST_BRANCH =~ 'version-bump' ]]; then
      if [[ "$(git diff HEAD^ | grep -e '^[-+][0-9]' | sed 's/^[+\-]//' | sed 's/\.[0-9]*$//' | uniq | wc -l)" -eq 2 ]]; then
        clone_dir=$(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
        git clone --depth 1 https://$GITHUB_TOKEN@github.com/slamdata/devtools.git $clone_dir

        for t in "$(scripts/listLabels | grep 'version: revision')"; do
          $clone_dir/bin/sdmerge $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST
        done
      fi
    fi

  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
